dir = File.expand_path('../..', __FILE__)
$:.unshift(dir) unless $:.include?(dir)
# This file was generated by the `rspec --init` command. Conventionally, all
# specs live under a `spec` directory, which RSpec adds to the `$LOAD_PATH`.
# Require this file using `require "spec_helper"` to ensure that it is only
# loaded once.
#
# See http://rubydoc.info/gems/rspec-core/RSpec/Core/Configuration

ENV['RACK_ENV'] = 'test'
ENV['DATABASE_URL'] = 'sqlite3::memory:'

require 'keyfile/app'  # <-- your sinatra app
require 'rspec'
require 'rack/test'
require 'database_cleaner'

RSpec.configure do |config|

  # Run specs in random order to surface order dependencies. If you find an
  # order dependency and want to debug it, you can fix the order by providing
  # the seed, which is printed after each run.
  #     --seed 1234
  config.order = 'random'

  ActiveRecord::Base.logger = nil

  config.before(:suite) do
    silence_stream($stdout) do
      ActiveRecord::Migrator.migrate(ActiveRecord::Migrator.migrations_paths.first, nil)
    end
  end

  DatabaseCleaner.strategy = :truncation
  config.before(:each) do
    DatabaseCleaner.clean!
  end
end
